### ISSUE TITLE
Getting Error "[avformat_open_input] Unknown error occurred (-1313558101)"

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#378] opened 2023-11-28 15:01 UTC
same stream is playing in vlc but ost of the times in flyleaf getting "[avformat_open_input] Unknown error occurred (-1313558101)"

LOGS:

20.25.35.982 | Info  | [#1]     [DecoderContext] [OpenPlaylistItem] None =>  [Error: [avformat_open_input] Unknown error occurred (-1313558101)]
20.25.35.982 | Info  | [#1]     [DecoderContext] [Open] srt://43.205.199.244:1022  [Error: [avformat_open_input] Unknown error occurred (-1313558101)]
20.25.39.510 | Info  | [#1]     [Player        ] Opening srt://43.205.199.244:1022
20.25.39.510 | Debug | [#1]     [Player        ] Initializing
20.25.39.510 | Debug | [#1]     [Player        ] Initialized
20.25.39.512 | Info  | [#1]     [PluginHandler ] [OpenDefault] Open Success
20.25.39.512 | Info  | [#1]     [PluginHandler ] SuggestItem #0 - 
20.25.39.512 | Info  | [#1]     [PluginHandler ] [OpenDefault] Open Item (0) Success
20.25.39.512 | Debug | [#1]     [Demuxer:  Main] Stopped -> Opening
20.25.39.512 | FFmpeg | Debug   | [NULL @ 000002338c47ac80] Opening 'srt://43.205.199.244:1022' for reading
20.25.39.512 | FFmpeg | Debug   | [srt @ 000002338c4ac080] No default whitelist set
20.25.39.513 | FFmpeg | Error   | [srt @ 000002338c4ac080] Success
20.25.39.514 | Debug | [#1]     [Demuxer:  Main] Opening -> Stopped
20.25.39.514 | Info  | [#1]     [Demuxer:  Main] Disposed
20.25.39.514 | Info  | [#1]     [DecoderContext] [OpenPlaylistItem] None =>  [Error: [avformat_open_input] Unknown error occurred (-1313558101)]
20.25.39.514 | Info  | [#1]     [DecoderContext] [Open] srt://43.205.199.244:1022  [Error: [avformat_open_input] Unknown error occurred (-1313558101)]

**Comment by saman1832** [comment] 2023-11-28 15:03
@SuRGeoNix  in what case this error comes.
And if inside playeropencomplete event this error or any error comes I used to call player.openasync(url) inside task.run but again same error is coming.

**Comment by SuRGeoNix** [comment] 2023-11-28 16:04
@saman1832 The error comes from FFmpeg so I can't tell you much. Enable Trace/MaxOffset log level (both flyleaf/ffmpeg). Check your firewall as you might need to added your application as an exception (especially when you access no common ports such as 1022). The Url is not working at all for me so I cannot reproduce it.

**Comment by saman1832** [comment] 2023-11-28 16:07
Ok, will try and update.
Actually the url is stopped from server side as of now.
Will let you know once it is up.

**Comment by SuRGeoNix** [comment] 2023-12-06 09:58
@saman1832 closing this, let me know if you still have issues so I will review this

**Closed by SuRGeoNix** 2023-12-06 09:58 UTC
