### ISSUE TITLE
Screen scaling / zoom / dpi calculations for proper rendering

### ISSUE THREAD

**Issue by huangli321456** [SuRGeoNix/Flyleaf#59] opened 2021-08-05 01:48 UTC
wpf:Layout exception in Viewbox
`<Window
......
Height="450" Width="800">
<Viewbox>
        <Grid Height="450" Width="800">
            <fl:VideoView x:Name="flview">
                <Grid>
                    <Image Source="NoneCCTV.png"/>
                </Grid>
            </fl:VideoView>
        </Grid>
    </Viewbox>
</Window>`

**Comment by SuRGeoNix** [comment] 2021-08-05 06:59
I don't see an Layout exception, I'm not familiar with viewbox at all. Can you provide more information and the exception message?
![image](https://user-images.githubusercontent.com/57474895/128305736-78e18898-2be3-4a9b-9b07-d8d447fe72f9.png)

**Comment by huangli321456** [comment] 2021-08-05 07:49
just like this,and run the application
![image](https://user-images.githubusercontent.com/13757973/128312363-74f7390c-caeb-41b8-a491-28e1e8d4ea54.png)

**Comment by huangli321456** [comment] 2021-08-05 07:54
I have solved this problem. You can refer to my practice
[WPF.zip](https://github.com/SuRGeoNix/Flyleaf/files/6936958/WPF.zip)

**Comment by SuRGeoNix** [comment] 2021-08-05 08:17
OK I see your point. Those two files are based on libvlcsharp from [here](https://github.com/videolan/libvlcsharp/blob/3.x/src/LibVLCSharp.WPF/VideoView.cs) and [here](https://github.com/videolan/libvlcsharp/blob/3.x/src/LibVLCSharp.WPF/ForegroundWindow.cs)

So the issue is with DPI? If you feel confident I will review it and I will update this to the next version.

**Comment by huangli321456** [comment] 2021-08-05 08:48
those two files are here
![image](https://user-images.githubusercontent.com/13757973/128321165-7d719daa-fa81-49f8-acba-8af9797081fb.png)

not only DPI,the basic window size also affects the viewbox and indirectly the videoview
so you need to calculate the zoom ratio between the current screen and the design size of the base window
for example , your screen bound is 1920x1080,but base window size is design to 3840x2160,and system zoom layout is not 100% like this
![image](https://user-images.githubusercontent.com/13757973/128319740-67b57927-e995-4ce8-9f0e-1aa5ac1129ad.png)
under these circumstances,DPI and basic window size will all affect it

**Comment by SuRGeoNix** [comment] 2021-08-05 09:16
This probably means that [Renderer](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaRenderer/Renderer.cs#L231) should also consider those factors. And I need also to ensure that doesn't brake anything else.

**Comment by SuRGeoNix** [comment] 2021-08-08 20:05
Hey, I tried to add this on v3.2 but the fix that you suggest didn't work for me. I didn't have time to do more research on  this. I will have a look at the next update

**Comment by SuRGeoNix** [comment] 2022-07-01 12:06
@huangli321456 I'm closing this as I cannot reproduce it anymore. Please re-open if you still have issues.

**Closed by SuRGeoNix** 2022-07-01 12:06 UTC
