### ISSUE TITLE
Fast Loading of RTSP Stream

### ISSUE THREAD

**Issue by lkinfotechai** [SuRGeoNix/Flyleaf#253] opened 2023-02-28 10:10 UTC
I am using rtsp server to serve stream to flyleaf player, 
when i start giving stream to flyleaf player then player takes almost 2-3 seconds for start stream play.

but on the other end  when the same process i give to libvlcsharp it takes only 1 second max to start the stream.

how we can make the stream load faster in flyleaf, any way?

**Comment by SuRGeoNix** [comment] 2023-02-28 10:37
Hi @lkinfotechai, try the following

``` csharp
Config.Demuxer.FormatOpt["probesize"] = (5 * (long)1024 * 1024).ToString(); // (Bytes) Default 5MB | Higher for weird formats (such as .ts?) and 4K/Hevc
Config.Demuxer.FormatOpt["analyzeduration"] = (5 * (long)1000 * 1000).ToString(); // (Microseconds) Default 5 seconds | Higher for network streams
```

**Comment by SuRGeoNix** [comment] 2023-03-09 17:37
I'm closing this. Let me know if you still have issues.

**Closed by SuRGeoNix** 2023-03-09 17:37 UTC

**Comment by lkinfotechai** [comment] 2023-03-10 06:55
hi, i have tested this but still no effect on speed of loading stream from RTSP.

**Comment by SuRGeoNix** [comment] 2023-03-10 07:56
If the issue is not with the ffmpeg options then probably it's related with this https://github.com/SuRGeoNix/Flyleaf/issues/162
