### ISSUE TITLE
Window Position Changes After Opening File

### ISSUE THREAD

**Issue by MrJacquers** [SuRGeoNix/Flyleaf#144] opened 2022-04-17 18:52 UTC
I've encountered a strange behaviour while using the VideoView inside my WPF app. Sometimes after opening a file via the open file dialog the window position changes, usually jumping toward the bottom and sometimes to the right as well. This only happens if the app isn't maximized. It also doesn't happen if I open the file directly without using the dialog.

Have you seen this behaviour before and do you have an idea of what may be causing it? Thanks.

Edit: I'm able to make it do it now just by showing a OFD without opening a video (I'm using my own command). Weird!

**Comment by Jacques-eMediaIT** [comment] 2022-04-17 19:18
I've worked around it by toggling the VideoView's visibility, so you can close the issue if you want. Would be interesting to know why it happens though.

**Comment by Jacques-eMediaIT** [comment] 2022-04-17 20:39
I think I may have tracked it down. I saw that if I opened a file by double clicking on it in the file dialog then the issue happens, but not when selecting it and then clicking the dialog's open button. 

If I do the following it prevents the issue, but I lose some other functionality. So it seems like the double click of selecting the file is being picked up elsewhere and doing something?

Config.Player.MouseBindings.Enabled = false;

I thought I could toggle it before and after opening the file dialog, but I'm not able to enable / disable that setting once the player is already initialized, unless there's another way to do it?


The behaviour happens in the 'FlyleafPlayer (Custom - MVVM) (WPF)' project, but not the 'FlyleafPlayer (WPF Control) (WPF)' project, so there must be something different between the config of them.

**Comment by SuRGeoNix** [comment] 2022-04-17 23:02
Well I can't look it at it right now, but I guess the issue is with the mouse events. When you have enabled them, you can also drag the window. Somehow, it confuses the mouse down / drag positions. If you open you custom dialog try to disable the mouse bindings and enable them back when you close it? I will have a deeper look later on.

**Comment by SuRGeoNix** [comment] 2022-04-25 09:29
I was not able to reproduce it with the 'FlyleafPlayer (Custom - MVVM) (WPF)' project. Did you resolve it? In any case this should be handled by the application level. Let me know if I need to look something more specific.

**Comment by Jacques-eMediaIT** [comment] 2022-04-25 10:19
I was able to work around it, so it's fine.

**Closed** 2022-04-30 05:26 UTC
