### ISSUE TITLE
ShowFrame(0) does not work anymore in 3.7.42

### ISSUE THREAD

**Issue by f1nalspace** [SuRGeoNix/Flyleaf#420] opened 2024-01-23 08:46 UTC
We recently upgraded from FlyLeaf 3.6.7 (FFMPEG 5.1.1) to FlyLeav 3.7.42 (FFMPEG 5.1.2.3).
Now ShowFrame(0) does not present the first frame anymore, it stays black until we start playing or execute any seeking but we need to display the first frame of the video always.

**Comment by SuRGeoNix** [comment] 2024-01-24 08:50
@f1nalspace I cannot reproduce it. Does it happen with all the inputs or with specific ones? Can you provide more info/logs?

**Comment by SuRGeoNix** [comment] 2024-01-24 13:08
@f1nalspace I've just fixed an issue when used directly after Open that was might be related, If you can test from master otherwise when I release the next NuGet.

**Comment by SuRGeoNix** [comment] 2024-01-28 18:51
@f1nalspace This should be fixed with v3.7.43. Let me know if not so I will look into it.

**Closed by SuRGeoNix** 2024-01-28 18:51 UTC
