### ISSUE TITLE
Color Issue

### ISSUE THREAD

**Issue by kwanggaeto** [SuRGeoNix/Flyleaf#334] opened 2023-08-10 23:29 UTC
![image](https://github.com/SuRGeoNix/Flyleaf/assets/7101046/476e73a9-0428-4717-bbd6-af8e44ae166b)

↓ Video Information (i guess.. it is using MJPEG codec)
![image](https://github.com/SuRGeoNix/Flyleaf/assets/7101046/f1ccc026-4785-48b8-98d1-ea18dd5f9d00)

hi, again. i faced a color issue. some video display wrong color. i didn't change any options.

the left player in the capture shot above is your released vesion player. the right is the 'pot player'(you can find and download in internet). also, the player i'm making has the same problem.

**Comment by SuRGeoNix** [comment] 2023-08-11 09:05
Hey @kwanggaeto, would be possible to send/email me a sample video with this issue so I can review this easier?

**Comment by kwanggaeto** [comment] 2023-08-17 00:24
> Hey @kwanggaeto, would be possible to send/email me a sample video with this issue so I can review this easier?

ok. i sent an email to you

**Comment by SuRGeoNix** [comment] 2023-08-17 09:32
Hi @kwanggaeto, just check the samples and I couldn't reproduce it. Both videos play the same for me (same as potplayer too).
Can you send me a flyleaf's debug log while you open the videos to see the details? (mainly I guess for you it uses video acceleration while for me it doesn't and that's why you have different results)

**Comment by SuRGeoNix** [comment] 2023-09-01 22:54
Closing this but re-open it by providing me more info so I can review it

**Closed by SuRGeoNix** 2023-09-01 22:54 UTC
