### ISSUE TITLE
[WPF] Fullscreen doesn't hide taskbar

### ISSUE THREAD

**Issue by M0n7y5** [SuRGeoNix/Flyleaf#36] opened 2021-05-05 02:00 UTC
When i doubleclick or click on fullscreen button it wont hide taskbar from windows. 
Tested in my app and latest compiled example.

**Comment by SuRGeoNix** [comment] 2021-05-05 06:05
Can't reproduce it. Can you get a dxdiag screenshot of system and display?

**Comment by SuRGeoNix** [comment] 2021-05-05 06:18
OK. Just did reproduce it. Happens when you are already in maximized state. I will have a look as fullscreen has generally still few issues

**Comment by SuRGeoNix** [comment] 2021-05-05 07:09
Should be fixed with the latest commit, if not let me know!

**Closed by SuRGeoNix** 2021-05-05 07:09 UTC
