### ISSUE TITLE
Possible handle leak when repeatedly create/play/stop/dispose flyleaf players

### ISSUE THREAD

**Issue by dev991301** [SuRGeoNix/Flyleaf#450] opened 2024-03-27 05:52 UTC
I am using FlyleafLib.Controls.WPF 1.3.8 via nuget on .NET 8.

I have written a WPF app that repeatedly creates/plays/stops/disposes flyleaf players. Over time, the process seems to leak handles as shown in Performance Monitor:
![ReleaseHandleLeakGraph](https://github.com/SuRGeoNix/Flyleaf/assets/113315480/fa97331d-f252-414c-8d28-14a80ef48481)

I have made the code available in the github repo [FlyleafCycleTest](https://github.com/dev991301/FlyleafCycleTest)

Can you replicate the handle leak or is it particular to my system?

**Comment by arslan38** [comment] 2024-04-02 15:25
+

**Comment by t3therdev** [comment] 2024-04-03 13:56
we are also seeing memory leaks on our side. @SuRGeoNix

**Comment by SuRGeoNix** [comment] 2024-04-03 16:14
I will review this in the weekend

**Comment by t3therdev** [comment] 2024-04-08 13:24
hi @SuRGeoNix were you able to take a look into this?

**Comment by SuRGeoNix** [comment] 2024-04-09 11:03
@dev991301 does this happen with trace log off? I cannot reproduce it so far

**Comment by dev991301** [comment] 2024-04-09 23:48
> @dev991301 does this happen with trace log off? I cannot reproduce it so far (can you use the release's ffmpeg libraries?)

@SuRGeoNix It does seem to happen with trace off. I am using the FFmpeg libraries that come from the Flyleaf 3.7.16 release. It also doesn't seem to matter if video acceleration is enabled or disabled. 

![ReleaseHandleLeakGraph_TraceOff_VA](https://github.com/SuRGeoNix/Flyleaf/assets/113315480/abd797ec-179b-4a4d-8c8e-7b825186fbbd)

In the Github code I submitted, would you be able to uncomment the other players in MainWindow.xaml and see what the handle count trend looks like?

![MainWindow_xaml](https://github.com/SuRGeoNix/Flyleaf/assets/113315480/c5126d14-622c-4130-895c-8d5351165a5b)

**Comment by SuRGeoNix** [comment] 2024-04-10 08:00
Here my results with 9 players:-

![image](https://github.com/SuRGeoNix/Flyleaf/assets/57474895/0a95fbdc-cd93-4669-aecc-6d5b9e769c75)

**Comment by t3therdev** [comment] 2024-04-11 14:40
@SuRGeoNix did you leave it running for a long period of time?

**Comment by SuRGeoNix** [comment] 2024-04-11 15:36
@t3therdev about 30'

**Comment by SuRGeoNix** [comment] 2024-05-06 08:23
Guys, any news with this one? I couldn't reproduce it also in systems with different GPUs.

**Comment by dev991301** [comment] 2024-05-06 10:28
I think the handle growth on my machines may be related to the version of the integrated Intel graphics drivers I am using. Running with an old version of a graphics driver the handles didn't grow (version 27.20.100.9079 which came from HP) but when upgraded to a newer Intel driver it did grow (version 31.0.101.5382). It also grew on a machine running Intel UHD graphics around version 31.0.x.x vintage. But it didn't grow when running off the NVIDIA graphics.

**Comment by SuRGeoNix** [comment] 2024-05-06 12:23
Everything points to GPU / drivers so I'm not sure if there is anything left from Flyleaf side to fix. I had different issues with RX 580 and had to use older drivers to make it work properly. So I'm afraid I will close this as is not related to the library.

**Closed by SuRGeoNix** 2024-05-06 12:23 UTC

**Comment by SuRGeoNix** [comment] 2024-05-08 07:33
Possible related WPF issue here dotnet/wpf/issues/7704

It would be interested to see if the problematic GPU/drivers having the same issue with WinForms.
