### ISSUE TITLE
WPF app getting crash

### ISSUE THREAD

**Issue by saman1832** [SuRGeoNix/Flyleaf#396] opened 2023-12-23 11:34 UTC
Playing 10 players simultaneously and it's working fine but if making internet off then on after 10 secs app getting crash.
Getting below errror
![IMG_20231223_170155](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/b37380c3-899b-438b-9393-7856b36dcee5)

**Comment by SuRGeoNix** [comment] 2023-12-23 11:44
@saman1832 please I cannot ask everytime for log file

**Comment by saman1832** [comment] 2023-12-23 12:08
@SuRGeoNix  sharing over the email.

**Comment by saman1832** [comment] 2023-12-23 12:24
[https://drive.google.com/file/d/1O5iHYJDHlaIjgmVez-Jfd-PXhJl6Qnn5/view?usp=sharing](url)

Log file url.

**Comment by SuRGeoNix** [comment] 2023-12-23 13:04
@saman1832 What I can see from logs

1) This is probably not related with multiple players, it could just happen with only one
2) Root cause of the issue seems to be the 0x80070057 there is also an open issue in Kodi xbmc/xbmc/issues/24088
3) By disabling the Video/Hardware acceleration might fix the issue

Closing this as this seems to be an FFmpeg issue

**Closed by SuRGeoNix** 2023-12-23 13:04 UTC

**Comment by saman1832** [comment] 2023-12-23 13:37
By disabling the Video/Hardware acceleration might fix the issue>> fixes the issue but cpu is getting more high,
As well video is getting gray after making hardware acceleration false.
![aa](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/adf0df53-74d0-4f8a-9ea4-bddfe1280387)


**NOTE: And app crashing is not happening on all machine**

**Comment by SuRGeoNix** [comment] 2023-12-23 13:44
@saman1832 It's normal to have high CPU without hardware acceleration. It is also seems that this issue is related with HEVC 
 (h.265) so I would also consider switching to AVC (h.264) at the source (cameras?) so I would be able to have both hardware acceleration and no crashes.

**Comment by saman1832** [comment] 2023-12-23 23:16
What if you apply try catch block in this method.
Might exception gets handled.

![IMG_20231223_170155](https://github.com/SuRGeoNix/Flyleaf/assets/49141964/89b2c837-6bee-4478-91f8-7b2d51c0dba6)

**Comment by SuRGeoNix** [comment] 2023-12-24 07:00
I don't think try catch will catch the access violation. As I cannot reproduce it and you already can debug it, see if you can find a workaround and create a pull request.
