### ISSUE TITLE
VideoView in ScrollViewer not properly rendering

### ISSUE THREAD

**Issue by rebelmx4** [SuRGeoNix/Flyleaf#170] opened 2022-06-28 07:46 UTC
![image](https://user-images.githubusercontent.com/7813353/176123550-d65a1e5a-a900-41c8-a9bb-f73bc045d9af.png)

**Comment by SuRGeoNix** [comment] 2022-06-28 10:35
Hi @rebelmx4, this probably related / duplicate to #149

I will try later to reproduce it and just confirm it.

**Comment by rebelmx4** [comment] 2022-06-29 06:35
i use flyleaf in wpf

**Comment by SuRGeoNix** [comment] 2022-06-29 13:17
Hi @rebelmx4, I tried to reproduce it. The problem was with the Front Window which is used for the player's front content and not the actual video. You might be able to handle this be changing the front window's visibility to false when the it's partial or full scrolled? Can you confirm that your issue is only with front window and not with the WinFormHost(video)?

**Comment by SuRGeoNix** [comment] 2022-06-29 13:53
Found the related issue with WindowsFormHost [here](https://stackoverflow.com/questions/14080580/scrollviewer-is-not-working-in-wpf-windowsformhost)

I will try to implement this on the upcoming updates

**Comment by SuRGeoNix** [comment] 2022-06-29 15:52
If you can test this from master and let me know if the fix works for you. Otherwise wait for the next nuget package update to test it.

**Comment by rebelmx4** [comment] 2022-07-01 03:00
I already tesed code of master, it is OK!!!!
it is the first time that i post iusse, I'm surprised you responded so quickly. thank you very much.
but i meet another problem. Only part of picture can be present sometime. 
![image](https://user-images.githubusercontent.com/7813353/176814778-510f0d97-2a42-46d2-aaad-4a9c9d786933.png)

**Comment by SuRGeoNix** [comment] 2022-07-01 04:40
No problem @rebelmx4. Is this another issue or related with the scroll viewer? Do you see anything at Flyleaf's logs?

**Comment by rebelmx4** [comment] 2022-07-01 05:35
how to see  Flyleaf's logs?
it probably is related width the scroll view.
this view is used to preview video. when the mouse enter a thumb. i attach VideoView to grid which is parent of thumb.
After i scroll this view, occasionally occur this case when the mouse enter a thumb.

**Comment by SuRGeoNix** [comment] 2022-07-01 05:50
Check the Engine.Start() from samples to see how you can enable logging. But yes probably that's related with the scroll viewer. If I cannot reproduce it I will not be able to fix it. You can use this if you know when it happens (on the player that mouse enter fires):-

```csharp
Player.VideoView.WinFormsHost.ResetRegion();
```

**Comment by SuRGeoNix** [comment] 2022-07-01 09:01
Hey @rebelmx4, can post your xaml or can you tell me what do you do exactly when you preview the video, does the VideoView still have the scroll viewer as a parent?

**Comment by rebelmx4** [comment] 2022-07-01 09:19
[thumb.zip](https://github.com/SuRGeoNix/Flyleaf/files/9027665/thumb.zip)

thumb is used here
![image](https://user-images.githubusercontent.com/7813353/176864668-25aed64d-8927-4f75-9fff-595b6f40f09c.png)

I only create VideoView. When the mouse enter a thumb, i deattach VideoView from its parent and attach it to current thumb.
code is here  ( OnMouseEnter and OnMouseLeave  Thumb class )
![image](https://user-images.githubusercontent.com/7813353/176865651-734f55c2-b49c-4d3b-ae9e-30d83c5c8aa6.png)

**Comment by SuRGeoNix** [comment] 2022-07-01 09:30
Can you check with the latest commit?

**Comment by rebelmx4** [comment] 2022-07-01 10:05
the lastest commit does not have a partial rendering problem, but it have "cross viewport " problem.
![GIF](https://user-images.githubusercontent.com/7813353/176873808-c5ff09fa-4ce1-40bf-a57f-9d29b5fa6ab1.gif)

**Comment by rebelmx4** [comment] 2022-07-01 10:08
the lastest commit does not have a partial rendering problem, but it have "cross viewport " problem.
![GIF](https://user-images.githubusercontent.com/7813353/176874395-08adae73-e33d-4c57-b948-2ccd7178e019.gif)

**Comment by SuRGeoNix** [comment] 2022-07-01 10:30
OK that was my mistake, forgot an additional update, hopefully now it's fixed!

**Comment by SuRGeoNix** [comment] 2022-07-01 10:41
And one more tip. You can use the new GetBitmap2 from renderer to save the last frame as thumb (you can now specify also the size- height) and present it like 'continue watching'. Check also the Player.GetCurrentSession so you can continue playing from where the player stopped with the same streams.

**Comment by SuRGeoNix** [comment] 2022-07-01 11:46
No worries. Feel free to re-open an issue even just to ask for help ;)
Happy weekend

**Comment by rebelmx4** [comment] 2022-07-04 02:46
The above two issues have been fixed. thank you!!
yet there is a small issue. when the mouse enter, for a moment there is a twinkle.
![GIF](https://user-images.githubusercontent.com/7813353/177072653-0f0b2602-81bd-44e7-b2ed-21a13aef6e7e.gif)


In addition, i cant reopen the issue.
![image](https://user-images.githubusercontent.com/7813353/177072385-490b80de-eca4-461f-822e-7087da7b7287.png)

**Comment by SuRGeoNix** [comment] 2022-07-04 06:04
No worries. I will re-open it. I will try to review also this one until the next update.

**Comment by SuRGeoNix** [comment] 2022-07-09 11:21
I was not able to reproduce with a quick try. Is it possible that the overflow content are the image and not the player?

**Comment by SuRGeoNix** [comment] 2022-11-03 18:28
I'm closing this as the VideoView changed completely with the new FlyleafHost implementation. Give me some feedback when possible.

**Closed by SuRGeoNix** 2022-11-03 18:28 UTC
