### ISSUE TITLE
Release memory and clear screen when video finished

### ISSUE THREAD

**Issue by pubpy2015** [SuRGeoNix/Flyleaf#19] opened 2020-12-17 10:20 UTC
Hi,

Issue: 
1. Start programe => memory ~ 32MB
2. Play 4K video file => memory ~ 200 MB
3. Video Finished: memory still ~ 200 MB and last frame still display

To test I am create a method Close() on MediaDecoder.cs and Stop() on MediaRouter.cs but when press a key to stop video, the memory only reduce at 144 MB.

How to release all memory when stop video or video finished and clear screen (black color) at the end ?

// MediaRouter.cs
public void Stop()
        {
            decoder.Close();

            Close();
        }

// MediaDecoder.cs
public void Close()
        {
            video?.Dispose();
            video = null;
            audio?.Dispose();
            audio = null;
            if (swsCtx != null)
            {
                sws_freeContext(swsCtx);
                swsCtx = null;
            }
            if (vCodecCtx != null)
            {
                avcodec_close(vCodecCtx);
                vCodecCtx = null;
            }
            if (aCodecCtx != null)
            {
                avcodec_close(aCodecCtx);
                aCodecCtx = null;
            }
        }

**Comment by SuRGeoNix** [comment] 2020-12-17 17:17
I will try to create a proper stop even if flyleaf does not use it currently. In the meantime, have a look at MediaRouter.cs to free the queue frames (ClearVideoFrames). also in case of sws maybe you should also clean some buffers there in MediaDecoder.cs (outBufferPtr something).

**Comment by SuRGeoNix** [comment] 2021-03-04 18:54
I'm closing this, let me know if the new code done the job for you. In any case I'll not stop at the end for now, I will let the user choose whether to close it or re-seek / play

**Closed by SuRGeoNix** 2021-03-04 18:54 UTC

**Comment by synologic** [comment] 2022-01-29 12:35
Any progress on this ?

**Comment by SuRGeoNix** [comment] 2022-01-29 16:41
@synologic That's an old thread. What is your issue? If you want to release the memory at the end of a video you need to call Player.Stop()

**Comment by synologic** [comment] 2022-01-29 16:45
It is an old one yes :)
I am calling Player.Stop() however the memory is not freed and last frame remains on the player surface.
I'm using 3.4.7 from Nuget

**Comment by SuRGeoNix** [comment] 2022-01-29 16:53
Just tested again and it works fine (Sample on WinForms - Form1.cs)

```csharp
using FlyleafLib;
using FlyleafLib.MediaPlayer;

namespace WinFormsApp1
{
    public partial class Form1 : Form
    {
        Player Player { get; set; }
        public Form1()
        {
            Engine.Start(new EngineConfig()
            {
                FFmpegPath = @"c:\root\projects\Flyleaf\FFmpeg"
            });

            InitializeComponent();
            Player = new Player();
            Player.Control = flyleaf1;

            Player.Open(@"C:\root\dev\flyleaf\videosamples\0.mp4");
            Player.PlaybackCompleted += (o, e) =>
            {
                Player.Stop();
            };
        }
    }
}
```

**Comment by synologic** [comment] 2022-01-29 16:56
Maybe i should have mentioned, if it makes any difference. I'm playing a live RTSP stream, not a file and not waiting for completion.

I just call .Stop() in order to stop video or load another live stream.

Not sure if that changes anything :)

**Comment by SuRGeoNix** [comment] 2022-01-29 17:00
Yes, that makes a lot of difference :)

There is already an investigation from one of my users that has issues (memory leaks - not video memory).  It could be an ffmpeg bug (with udp protocol). However, I'm was not able to reproduce it yet. I just tried this one https://www.wowza.com/developer/rtsp-stream-test. Does this leak for you?

**Comment by synologic** [comment] 2022-01-29 17:04
I just upgraded to 3.4.9 and the memory gets freed once GC runs after .Stop() so that's that :)

The last frame still stays on the screen, for both Wowza's and my stream.

**Comment by SuRGeoNix** [comment] 2022-01-29 17:15
There is no difference between 3.4.7 and 3.4.9. Additionally, on my side I don't need to call GC to clear the memory.
Player.Stop clears the frame (leaves a black frame) and the memory, not sure what are you doing.

**Comment by synologic** [comment] 2022-01-29 17:34
Not doing anything fancy:
        public Form1()
        {
            InitializeComponent();

            Engine.Start(new EngineConfig()
            {
                FFmpegPath = ":",
                UIRefresh = true,
                UIRefreshInterval = 250
            });

            // Prepares Player's Configuration
            Config = new Config();
            Config.Player.KeyBindings.Enabled = false;

            Player = new Player(Config);

            Player.Control = flyleaf1;
            Player.Tag = "player1";

            Player.PropertyChanged += playerPropertyChanged;
        }

Then i just call OpenAsync("RTSP_STREAM") and when i'm done i just call .Stop().

The only other difference, between the wowza and my stream, is that i'm using H265

What i meant about the GC is that, once i call Stop() i see the memory being freed after a few seconds, so i assumed is the GC that frees it :)

**Comment by SuRGeoNix** [comment] 2022-01-29 17:43
Is it possible that you call Player.Stop before it actually Player.OpenAsync completes?
Do you seen any difference between wowza and your stream and you mention the different codec?
I don't force GC on Player.Stop it's true. I do this only on Dispose. But I guess it is not required there.

**Comment by SuRGeoNix** [comment] 2022-01-29 17:50
You can try the same code that I use to see if we have any difference:
Opens/Plays/Stops check if you see the black frame in between

```csharp
using FlyleafLib;
using FlyleafLib.MediaPlayer;

namespace WinFormsApp1
{
    public partial class Form1 : Form
    {
        Player Player { get; set; }
        public Form1()
        {
            Engine.Start(new EngineConfig()
            {
                FFmpegPath = @"c:\root\projects\Flyleaf\FFmpeg"
            });

            Player = new Player();
            InitializeComponent();
            Player.Control = flyleaf1;

            Task.Run(() =>
            {
                while (true)
                {
                    Player.Open(@"rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4");
                    Thread.Sleep(5000);
                    Player.Stop();
                    Thread.Sleep(5000);
                }
            });
        }
    }
}
```

**Comment by synologic** [comment] 2022-01-29 19:49
I'm sorry, but still the same thing.
I even upgraded to VS 2022 and migrated the solution to .NET 6, however it's the same thing, the last frame stays on screen after .Stop() is called

**Comment by SuRGeoNix** [comment] 2022-01-29 20:01
Well reviewing the code it could be possible, however not sure why it happens to you every time and it never happens to me.  I will fix it with the next update ;)

**Comment by synologic** [comment] 2022-01-29 20:06
Not sure, may be Windows 11 related issue, i can live with it, or maybe there's a way i can directly paint something on the surface after stop ? :)

**Comment by SuRGeoNix** [comment] 2022-01-29 20:12
Possible, with Player.Control you could mess with the background refresh/paint etc. But, I think I found the problem and it will be fixed with the next update. I'm disposing the lastframe after I refresh the renderer and it just happens to be null most of the times (for me).
